### ISSUE TITLE
Error with untouched Gulpfile.js

### ISSUE THREAD

**Issue by jeffadev** [mattmodrowski/quenchjs#17]
Below is the error I'm experiencing when **gulp** is ran. Yes, I have run **npm install**.

`throw new Error('libsass bindings not found. Try reinstalling node-sass?');`

It could just be a problem with the versions, but I've tried a lot to fix it and haven't seen much luck!

Thanks.

**Comment by swthate** [comment]
I'm getting a similar error. Here's my full error report:

```
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/Steven/Sites/wptest/wp-content/themes/timber-theme/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/Steven/Sites/wptest/wp-content/themes/timber-theme/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Steven/Sites/wptest/wp-content/themes/timber-theme/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Steven/Sites/wptest/wp-content/themes/timber-theme/gulpfile.js:10:12)
```

**Comment by jeffadev** [comment]
@swthate 

Yeah man it's because of incorrect versions of dependencies. My suggestion would be to go into `package.json`, and change all the dependency and/or dev-dependency versions to `'*'`. After you have done this, you should type in the console: `npm update --save`. Then, you can run `gulp` and you should be on your way.

Let me know if you have any trouble I'll help you out.

**Comment by seemc0** [comment]
Here's my solution to this issue:

npm uninstall --save-dev gulp-sass
npm install --save-dev gulp-sass@2

**Comment by jeffadev** [comment]
Haha, I think you shouldn't use this now, as it is incredibly outdated!
